import React from 'react';
import Head from 'next/head'
import Header from '../components/Header'
import Footer from './Footer';

export default props =>
{
    return(
        <div>
        <Head>
          <title>MetaVerse DAO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>
        {props.children}
        <Footer/>
        </div>
    );
};